services:
  psql:
    container_name: psql
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  static_volume:

